version: "3.9"
services:
  mongo:
    image: mongo:7
    container_name: bk_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  backend:
    build: ./backend
    container_name: bk_backend
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo
    ports:
      - "8000:8000"


  frontend:
    build: ./frontend
    container_name: bk_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"


volumes:
  mongo_data:
