version: "3.9"
services:
  backend:
    image: ${BACKEND_IMAGE:-betterkahoots-backend:latest}
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=8000
    ports:
      - "8000:8000"

