name: Build and deploy backend container to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  IMAGE: kimandrew712/betterkahoots-backend:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_3F90403246264E5FB93E24FD5DADE2E0 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_991975423ADB488CB7398A9CB6077028 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: env.IMAGE
          file: ./backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'betterkahoots'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_79BAAB841DCA4B31B1126CB9E1F428C6 }}
          images: 'index.docker.io/${{ env.IMAGE }}'
