name: Build and deploy backend container to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_FB07C291FAA64D22B062113D4854A9CF }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_2F14DE75A14A4FBDB7EB412E8872B64C }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_FB07C291FAA64D22B062113D4854A9CF }}/kimandrew712/betterkahoots-backend:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'betterkahoots'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2AC261B609AD4326965C0A3148F638FD }}
          images: 'index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_FB07C291FAA64D22B062113D4854A9CF }}/kimandrew712/betterkahoots-backend:${{ github.sha }}'
